[package]
name = "voronoi"
version = "0.1.0"
authors = ["Graham Kaemmer <graham.kaemmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab = "0.4.2"

[dev-dependencies]
rand = "0.7.2"
